In [2]:
import numpy as np
import matplotlib.pyplot as plt
# import plotly.express as px 
import math
import pandas as pd
from random import *

num = 290

구간 분할

In [3]:
def bound(temp):
    if temp == 25.1:
        b = 1
    elif temp == -3.9:
        b = 290
    elif temp > 25.1 or temp < -3.9:
        b = 999
    elif temp >= 0:
        b = (251 - int(temp * 10))
    elif temp <= 0:
        b = (251 + math.ceil(abs(temp * 10)))
        
    return b

기온 => 구간

In [4]:
f = open("data.txt", "r")

temp = []

while True:
    line = f.readline()
    if not line:
        break
    sp = line.split("\t")
    sp2 = []
    for x in sp:
        sp2.append(float(x))
    temp.append(sp2)
    
temp = np.copy(temp)
part = np.copy(temp)

for i, _ in enumerate(temp):
    for j, x in enumerate(temp[i]):
        part[i,j] = bound(x)
    
part

array([[221., 202., 258., ..., 290., 221., 215.],
       [224., 207., 261., ..., 999., 228., 214.],
       [228., 212., 264., ..., 999., 226., 212.],
       ...,
       [101.,  50., 103., ...,  83.,  85.,  57.],
       [105.,  55., 127., ...,  89.,  99.,  57.],
       [113.,  65., 127., ..., 102., 101.,  61.]])

추이행렬 제작

In [5]:
result = [[0]*num for i in range(num)]

for j in range(len(part[0])):
    for i in range(len(part) - 1):
        if(int(part[i][j]) == 999 or int(part[i+1][j]) == 999 ):
            continue
        x = result[int(part[i][j]) - 1][int(part[i+1][j]) - 1]
        if(int(part[i][j]) - 1 <= int(part[i+1][j]) - 1):
            result[int(part[i][j]) - 1][int(part[i + 1][j]) - 1] = x + 1
            


temp = 0
total = []

for i in range(len(result)):
    temp = 0.0
    for j in range(len(result[0])):
        temp += result[i][j]
    total.append(temp)
    

for i, _ in enumerate(result):
    for j, data in enumerate(result[i]):
            temp = data / total[i]
            result[i][j] = temp

mc = np.copy(result)

for i, _ in enumerate(mc):
    temp = 0
    for j, data in enumerate(mc[i]):
        temp += data
    print(temp)

mc

#for i, data in enumerate(total):
    #print(str(round(25.0 - 0.1 * i, 2)) + ", " + str(data))
        


1.0
1.0
1.0
1.0
0.9999999999999999
1.0000000000000002
1.0
0.9999999999999998
1.0000000000000002
0.9999999999999996
1.0
1.0000000000000002
0.9999999999999996
0.9999999999999998
1.0
1.0000000000000002
1.0000000000000004
1.0
0.9999999999999998
0.9999999999999997
0.9999999999999999
1.0
0.9999999999999999
1.0000000000000002
0.9999999999999998
0.9999999999999998
0.9999999999999999
1.0
0.9999999999999998
1.0
1.0000000000000002
0.9999999999999999
1.0000000000000002
1.0000000000000002
0.9999999999999998
1.0000000000000002
1.0000000000000002
0.9999999999999996
1.0
1.0
1.0
0.9999999999999997
1.0
0.9999999999999999
0.9999999999999997
1.0000000000000002
1.0000000000000002
1.0
1.0000000000000002
1.0000000000000002
1.0
0.9999999999999997
0.9999999999999999
0.9999999999999997
0.9999999999999997
1.0
1.0000000000000002
1.0000000000000002
0.9999999999999999
1.0
1.0000000000000002
1.0
0.9999999999999999
1.0000000000000002
1.0000000000000002
1.0
0.9999999999999999
0.9999999999999997
0.9999999999999998
1.0


array([[0.16      , 0.        , 0.08      , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.08333333, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.4       ,
        0.6       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.33333333,
        0.66666667],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
x = np.zeros(num)

for j in range(num):
    for k in range(num):
        x[j] += mc[j, k]
            
for j in range(num):
    for k in range(num):
        mc[j, k] /= x[j]
        
mc_ot = np.zeros((24, num, num))
mc_ot[0] = mc
for i in range(1, 24):
    mc_ot[i] = np.dot(mc_ot[i-1], mc_ot[0])


In [8]:
mc_ot[2]

array([[0.004096  , 0.        , 0.002048  , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.04444444,
        0.95555556],
       [0.        , 0.        , 0.        , ..., 0.        , 0.03703704,
        0.96296296],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [9]:
time = int(input('알고 싶은 시간?: '))
temp = float(input('알고 싶은 온도?: '))
b = bound(temp)
x = np.arange(num) + 1
columns = ['Probability']
df = pd.DataFrame(mc_ot[time - 1,b - 1], index = x, columns = columns)
sr = pd.Series(x, index = x)
df['Boundary'] = sr

fig = px.bar(df, x = 'Boundary', y = 'Probability')
fig.show()

알고 싶은 시간?:  2
알고 싶은 온도?:  6


NameError: name 'px' is not defined

In [9]:
temp_pre = float(input("현재 온도를 입력하세요: "))
time = int(input("알고싶은 시간을 입력하세요: "))
temp_kn = float(input("알고 싶은 온도 이하는?: "))
x1 = bound(temp_pre)
x2 = bound(temp_kn)

print(x1)
print(x2)
result = 0.0

    
for i in range(x2, num):
    result += mc_ot[time - 1, x1, i]
    
print(str(temp_pre) + "도 에서 " + str(time) + "시간 후 " + str(temp_kn) + "도 이하로 내려갈 확률은 " + str(round(result * 100, 4)) + "%")

현재 온도를 입력하세요: 2
알고싶은 시간을 입력하세요: 6
알고 싶은 온도 이하는?: -2
231
271
2.0도 에서 6시간 후 -2.0도 이하로 내려갈 확률은 5.4492%


In [519]:
def bound_inv(state):
    x2 = round((252 - state) / 10.0, 2)
    x1 = round(x2 - 0.1, 2)
        #print('state: ' +  str(state_2) + ' x1: ' + str(x1) + ' x2: '  + str(x2))
    
    yield x1
    yield x2

검증

In [577]:
data = pd.read_csv("C:\\Users\\zuni1\\OneDrive - 서울대학교\\문서\\연구실\\jh\\data.csv", sep = ",", encoding = 'ISO-8859-1')
del(data['name'])
gap = []
gap.append(-99)
for i, temp in enumerate(data['temperature']):
    if(i+1 == len(data['temperature'])):
        break
    gap.append(round(data['temperature'][i+1] - data['temperature'][i], 2))


data['gap'] = gap
df = data[data['gap']<= 0]

df = df.reset_index()

df



index  point              date  temperature   gap
0        0    146   2019-03-01 0:00          3.6 -99.0
1        1    146   2019-03-01 1:00          3.5  -0.1
2        2    146   2019-03-01 2:00          2.9  -0.6
3        3    146   2019-03-01 3:00          2.8  -0.1
4        5    146   2019-03-01 5:00          2.6  -0.4
..     ...    ...               ...          ...   ...
890   1459    146  2019-04-30 19:00         16.3  -2.2
891   1460    146  2019-04-30 20:00         14.5  -1.8
892   1461    146  2019-04-30 21:00         13.5  -1.0
893   1462    146  2019-04-30 22:00         12.9  -0.6
894   1463    146  2019-04-30 23:00         12.9   0.0

[895 rows x 5 columns]

In [530]:
mc_cumulative = np.copy(mc_ot)

for i in range(len(mc_cumulative)):
    for j in range(len(mc_cumulative[0])):
        for k in range(1, len(mc_cumulative[0, 0])):
            mc_cumulative[i, j, k] += mc_cumulative[i, j, k - 1]


In [531]:
state = {'state 1': [], 'state 2': [], 'temperature_simulated': []}
for t in df['temperature']:
    state_1 = bound(t)
    x = random()
    state_2 = 0
    if(state_1 == 999):
        state['state 1'].append(state_1)
        state['state 2'].append(state_1)
        state['temperature_simulated'].append(state_1)
        continue
    while(x > mc_cumulative[0, state_1, state_2]):
        state_2 += 1
    state['state 1'].append(state_1)
    state['state 2'].append(state_2)
    
    boundary = bound_inv(state_2)
    
    x1 = next(boundary)
    x2 = next(boundary)

    temp_sim = uniform(x1, x2)
    state['temperature_simulated'].append(temp_sim)

print(len(state['state 1']))
print(len(state['state 2']))
print(len(state['temperature_simulated']))
df_state = pd.DataFrame(state)
df_state


895
895
895


state 1  state 2  temperature_simulated
0        215      217               3.445087
1        216      217               3.449274
2        222      227               2.482150
3        223      225               2.682224
4        225      229               2.281076
..       ...      ...                    ...
890       88       92              15.998379
891      106      108              14.343415
892      116      121              13.088843
893      122      131              12.031637
894      122      125              12.671932

[895 rows x 3 columns]

In [573]:
df2 = pd.concat([df, df_state], axis=1)
df3 = df2[df2['temperature_simulated'] < 999]

gap = []

    
del(df3['index'])
del(df3['point'])
del(df3['gap'])

x = df3['temperature'][0]
for i, temp in enumerate(df3['temperature']):
    if (i+1 == len(df3['temperature'])):
        break
    g = temp - x
    gap.append(g)
    x = temp
    
gap.append(2)
    
df3['gap'] = gap
df3

df4 = df3[df3['gap'] <= 0]
df4.reset_index()
df3.to_csv("C:\\Users\\zuni1\\OneDrive - 서울대학교\\문서\\연구실\\jh\\result3.csv")


C:\Users\zuni1\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



50% 넘는 구간 찾기

In [572]:
x = 0.0
most = 0

fout = open("C:\\Users\\zuni1\\OneDrive - 서울대학교\\문서\\연구실\\jh\\over_50.txt", "w+")

for i, _ in enumerate(mc_ot):
    for j, _ in enumerate(mc_ot[0]):
        x = 0.0
        for k in range(j, len(mc_ot[0,0])):
            x = 0.0
            for l in range(k, len(mc_ot[0,0])):
                x += mc_ot[i,j,l]
                if(x >= 1):
                    b1 = bound_inv(j + 1)
                    b2 = bound_inv(k + 1)
                    b3 = bound_inv(l + 1)
                    next(b1)
                    next(b2)
                    temp1 = next(b1)
                    temp2_2 = next(b2)
                    temp2_1 = next(b3)
                    fout.write("Time: " + str(i + 1)  + " , " + str(temp1) + " -> " + str(temp2_1) + " ~ " + str(temp2_2) + " , probability: " + str(round(x, 2)) + "\n")
                    print(str(j) + ", " + str(k) + ", " + str(l))
                    break
            
fout.close()

0, 0, 27
1, 1, 43
1, 2, 43
2, 2, 26
2, 3, 26
3, 3, 24
4, 4, 35
5, 5, 28
6, 6, 44
8, 8, 38
9, 9, 83
10, 10, 37
10, 11, 37
12, 12, 37
13, 13, 38
13, 14, 38
14, 14, 45
14, 15, 45
17, 17, 33
17, 18, 33
17, 19, 33
17, 20, 33
17, 21, 33
19, 19, 51
20, 20, 53
21, 21, 59
22, 22, 54
22, 23, 54
24, 24, 51
24, 25, 51
24, 26, 51
24, 27, 51
25, 25, 58
25, 26, 58
25, 27, 58
25, 28, 58
25, 29, 58
27, 27, 68
27, 28, 68
29, 29, 57
30, 30, 66
30, 31, 66
30, 32, 66
30, 33, 66
30, 34, 66
31, 31, 87
31, 32, 87
31, 33, 87
31, 34, 87
32, 32, 78
33, 33, 74
34, 34, 62
36, 36, 77
37, 37, 78
38, 38, 71
38, 39, 71
38, 40, 71
39, 39, 67
40, 40, 69
41, 41, 67
42, 42, 73
43, 43, 72
43, 44, 72
46, 46, 74
47, 47, 91
48, 48, 97
49, 49, 90
50, 50, 76
51, 51, 91
52, 52, 77
53, 53, 87
54, 54, 166
55, 55, 105
56, 56, 119
58, 58, 101
59, 59, 89
60, 60, 104
60, 61, 104
61, 61, 122
62, 62, 108
63, 63, 96
64, 64, 117
64, 65, 117
65, 65, 104
66, 66, 97
67, 67, 144
68, 68, 103
69, 69, 118
70, 70, 102
71, 71, 121
72, 72, 103
74, 

In [10]:
a = {'s': [1, 2, 3], 'd': [2, 3, 4]}
df = pd.DataFrame(a)
